USE DATABASE {{ database }};
USE SCHEMA {{ schema }};


CREATE OR REPLACE TABLE EMPLOYEE(
    EMPLOYEE_ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
    EMPLOYEE_NAME STRING,
    EMPLOYEE_HIRED_DATE DATE,
    EMPLOYEE_DPT_ID INTEGER,
    EMPLOYEE_JOB_ID INTEGER
)CLUSTER BY (EMPLOYEE_NAME, EMPLOYEE_ID);


COPY INTO EMPLOYEE (EMPLOYEE_NAME, EMPLOYEE_HIRED_DATE, EMPLOYEE_DPT_ID, EMPLOYEE_JOB_ID) FROM (
    SELECT
           e.$2 AS EMPLOYEE_NAME,
           e.$3  as EMPLOYEE_HIRED_DATE,
           e.$4 AS EMPLOYEE_DPT_ID, 
           e.$5 AS EMPLOYEE_JOB_ID
    FROM @employee_stage (file_format => api_data) e
);



CREATE OR REPLACE TABLE DEPARTMENTS(
 DEPARTMENT_ID  INTEGER AUTOINCREMENT START 1 INCREMENT 1,
 DEPARTMENT_NAME STRING
);
  

COPY INTO DEPARTMENTS (DEPARTMENT_NAME )FROM(
SELECT 
       d.$2 AS DEPARTMENT_NAME
FROM @department_stage (file_format => api_data) d ) ;



CREATE OR REPLACE TABLE JOBS(
 JOB_ID INTEGER  AUTOINCREMENT START 1 INCREMENT 1,
 JOB_NAME STRING
);
  

COPY INTO JOBS (JOB_NAME )FROM(
SELECT
       j.$2 AS JOB_NAME
FROM @jobs_stage (file_format => api_data) j ) ;
