USE DATABASE {{ database }};
USE SCHEMA {{ schema }};

CREATE OR REPLACE SEQUENCE seq1  START = 1 INCREMENT = 1;

CREATE OR REPLACE TABLE EMPLOYEE(
EMPLOYEE_ID INTEGER DEFAULT seq1.NEXTVAL,
EMPLOYEE_NAME STRING,
EMPLOYEE_HIRED_DATE DATE,
EMPLOYEE_DPT_ID INTEGER,
EMPLOYEE_JOB_ID INTEGER
)CLUSTER BY (EMPLOYEE_NAME, EMPLOYEE_ID);


COPY INTO EMPLOYEE FROM(
SELECT seq1.NEXTVAL,
       e.$2 AS EMPLOYEE_NAME,
       e.$3  as EMPLOYEE_HIRED_DATE,
       e.$4 AS EMPLOYEE_DPT_ID, 
       e.$5 AS EMPLOYEE_JOB_ID
FROM @employee_stage (file_format => employee_data) e ) ;



CREATE OR REPLACE TABLE DEPARTMENTS(
 DEPARTMENT_ID INTEGER,
 DEPARTMENT_NAME STRING
);
  

COPY INTO DEPARTMENTS FROM(
SELECT d.$1 AS DEPARTMENT_ID,
       d.$2 AS DEPARTMENT_NAME
FROM @department_stage (file_format => employee_data) d ) ;



CREATE OR REPLACE TABLE JOBS(
 JOB_ID INTEGER,
 JOB_NAME STRING
);
  

COPY INTO JOBS FROM(
SELECT j.$1 AS JOB_ID,
       j.$2 AS JOB_NAME
FROM @jobs_stage (file_format => employee_data) j ) ;